Update colour.py
Mecha-Karen/MechaK pull request #4
Opened 2021-09-02 07:13 UTC by AryamanSrii

added two new colors to provide users desirable colors

2021-09-02 08:23 UTC, Tweak4141 requested changes
Python comments.

2021-09-02 08:23 UTC, Tweak4141 commented on discord/colour.py
> +        return cls(#33cccc)
```suggestion
        return cls(0x33cccc)
```

2021-09-02 08:23 UTC, Tweak4141 commented on discord/colour.py
> +        return cls(#ff872)
```suggestion
        return cls(0xFF872)
```

2021-09-04 10:46 UTC, Tweak4141 approved these changes

2021-09-04 10:52 UTC, Seniatical commented
Looks good

2021-09-04 10:52 UTC, merged